version: "1.0"
services:

  prometheus:
    image: prometheus_spring-boot:latest
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  gateway-service:
    image: gateway-service:1.0.0
    ports:
      - "9999:9999"
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"

  auth-service:
    image: auth-service:1.0.0
    ports:
      - "6666:6666"
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"

  crypto-service:
    image: crypto-service:1.0.0
    ports:
      - "8077:8077"
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"

  currency-service:
    image: currency-service:1.0.0
    ports:
      - "8088:8088"
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"

  future-service:
    image: future-service:1.0.0
    ports:
      - "8099:8099"
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
